server-name: 'server'
send-to: 'server1 server2'
server-name-in-chat: 'server'
ranks:
  admin:
    prefix: '&4[A]'
    weight: '10'
  moderator:
    prefix: '&3[M]'
    weight: '9'

mutes:
  example:
    duration: 50000
    start: 123989934