server-name: hub
send-to: plots
server-name-in-chat: '&e[Hub]'
local-format: '&f$server$&f$rank$&7$player$&7: &f'
global-format: '&f$server$&f$rank$&7$player$&7: &f'
mute-blocked-commands:
- kiss
- highfive
- hug
- me
- poke
ranks:
  donor:
    prefix: '&6[&a%amount%&6]'
    weight: '1'
  owner:
    prefix: '&e[O]'
    weight: '100'
  builder:
    prefix: '&2[B]'
    weight: '95'
  admin:
    prefix: '&4[A]'
    weight: '99'
  moderator:
    prefix: '&3[M]'
    weight: '98'
  trusted:
    prefix: '&9[T]'
    weight: '97'
  default:
    prefix: '&7[-]'
    weight: '96'