name: MGChatStandalone
version: 0.1.0.0
author: janie177
softdepend: [PermissionsEx]
main: com.minegusta.mgchatstandalone.main.Main
commands:
  whisper:
    usage: /Whisper [player]
    description: Private message a player.
    aliases: [msg, pm, tell, message]
    default: true
  mute:
    usage: /Mute [player] [duration(minutes)]
    description: Mute and unmute players.
    default: op
  unmute:
    usage: /Unmute [player]
    description: Mute and unmute players.
    default: op
  reply:
    usage: /Reply [message]
    aliases: [r]
    description: Send a message to the player that last whispered you.
    default: true