name: MGChatStandalone
version: 0.1.0.0
author: janie177
softdepend: [PermissionsEx, Factions, MGRacesRedone, HeroPvP]
depend: [MGLib]
main: com.minegusta.mgchatstandalone.main.Main
commands:
  whisper:
    usage: /Whisper [player]
    description: Private message a player.
    aliases: [msg, pm, tell, message]
    default: true
  mute:
    usage: /Mute [player] [duration(minutes)]
    description: Mute and unmute players.
    default: op
  unmute:
    usage: /Unmute [player]
    description: Mute and unmute players.
    default: op
  reply:
    usage: /Reply [message]
    aliases: [r]
    description: Send a message to the player that last whispered you.
    default: true
  fc:
    usage: /FC [message]
    aliases: [factionschat, factionchat, fchat, factionc, allychat, neutralchat, nc, ac]
    description: Toggle Faction Chat mode. Only works when Factions is enabled.
    default: op
  creload:
    usage: /Creload
    description: Reload the chat plugin.
    default: op
  chatinterface:
    usage: /ChatInterface <Name>
    description: Open a GUI for managing the chat for a player.
    default: op
  chatfilter:
    usage: /ChatFilter <on/off>
    description: Toggle the chat profanity filter on or off.
    default: true